server:
  port: ${PORT:0}

spring:
  application:
    name: api-serie
  data:
    mongodb:
      username: usr-serie
      password: pwd-serie
      database: serie-dev
      port: 27016
      host: mongo-serie
  zipkin:
    base-url: http://zipkin-container:9411
    enabled: true
    sender:
      type: rabbit
  rabbitmq:
    addresses: rabbitmq-container:5672
    virtual-host: app_host
    username: guest
    password: guest

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}